theme: jekyll-theme-cayman
title: [Bridging the Gap between Object and Image-level Representations for Open-Vocabulary Detection]
description: Object centric Open Vocabulary Object detector that demonstrates state-of-the-art results on Open Vocabulary COCO and LVIS benchmark datasets
